services:
  - type: web
    name: auto-music-mixer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python mix_generator_web.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SUNO_API_KEY
        sync: false
      - key: UDIO_API_KEY
        sync: false